# Generated by Django 3.2 on 2023-04-03 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_photo', models.ImageField(unique=True, upload_to='student/%y/%m/%d/')),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('seat_number', models.IntegerField(unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('division', models.CharField(choices=[('1', 'رياضة'), ('2', 'علوم'), ('3', 'ادبي')], max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentCollege', to='colleges.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_result', models.IntegerField(blank=True, default=0, null=True)),
                ('digital_art_result', models.IntegerField(blank=True, default=0, null=True)),
                ('hand_drawing_result', models.IntegerField(blank=True, default=0, null=True)),
                ('trial_result', models.IntegerField(blank=True, default=0, null=True)),
                ('up_to_level', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_result', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Student Results',
            },
        ),
        migrations.CreateModel(
            name='PracticeDrawingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ImageField(unique=True, upload_to='student/%y/%m/%d/')),
                ('practice_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sketch', to='exams.practicedrawingexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sketch_answer', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Student Answer Practice Drawing',
            },
        ),
        migrations.CreateModel(
            name='McqAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq', to='exams.mcqexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mcq', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Student Answer Mcq',
            },
        ),
        migrations.CreateModel(
            name='HandDrawingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ImageField(unique=True, upload_to='student/%y/%m/%d/')),
                ('hand_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_sketch', to='exams.handdrawingexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_sketch_answer', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Student Answer Hand Drawing',
            },
        ),
        migrations.CreateModel(
            name='DigitalDrawingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ImageField(unique=True, upload_to='student/%y/%m/%d/')),
                ('digital_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_sketch', to='exams.digitaldrawingexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_sketch_answer', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Student Answer Digital Drawing',
            },
        ),
    ]
