# Generated by Django 3.2 on 2023-04-13 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='National ID must be 14 digits', regex='^.{14}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='mcqanswer',
            unique_together={('student', 'question')},
        ),
    ]
