# Generated by Django 3.2 on 2023-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20230413_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaldrawinganswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='handdrawinganswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mcqanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicedrawinganswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='up_to_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('seat_number', 'national_id', 'phone_number')},
        ),
        migrations.AlterUniqueTogether(
            name='studentresults',
            unique_together={('user', 'mcq_result', 'digital_art_result', 'hand_drawing_result', 'trial_result')},
        ),
    ]
