# Generated by Django 3.2 on 2023-04-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='departments',
        ),
        migrations.AddField(
            model_name='collegedepartment',
            name='colleges',
            field=models.ManyToManyField(related_name='departments', to='colleges.College'),
        ),
    ]
