# Generated by Django 3.2 on 2023-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqexam',
            name='option2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcqexam',
            name='option3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
