# Generated by Django 3.2 on 2023-06-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.CharField(choices=[('user', 'User'), ('student', 'Student'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='user', max_length=10),
        ),
    ]
